require("core.autocmd.format")
require("core.autocmd.env_helper")
require("core.autocmd.restore_cursor")
require("core.autocmd.yank")
require("core.autocmd.treesitter")
require("core.autocmd.colorscheme_compat")
require("core.autocmd.context_gf")
require("core.autocmd.user_comment")
