return {
	--   'saghen/blink.pairs',
	--   version = '*', -- (recommended) only required with prebuilt binaries
	--
	--   -- download prebuilt binaries from github releases
	--   dependencies = 'saghen/blink.download',
	--   -- OR build from source, requires nightly:
	--   -- https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
	--   -- build = 'cargo build --release',
	--   -- If you use nix, you can build from source using latest nightly rust with:
	--   -- build = 'nix run .#build-plugin',
	--
	--   --- @module 'blink.pairs'
	--   --- @type blink.pairs.Config
	--   opts = {
	--     highlights = {
	--       enabled = true,
	--       -- requires require('vim._extui').enable({}), otherwise has no effect
	--       cmdline = true,
	--       -- set to { 'BlinkPairs' } to disable rainbow highlighting
	--       groups = { 'BlinkPairsOrange', 'BlinkPairsPurple', 'BlinkPairsBlue' },
	--       unmatched_group = 'BlinkPairsUnmatched',
	--
	--       -- highlights matching pairs under the cursor
	--       matchparen = {
	--         enabled = false,
	--         -- known issue where typing won't update matchparen highlight, disabled by default
	--         cmdline = false,
	--         -- also include pairs not on top of the cursor, but surrounding the cursor
	--         include_surrounding = false,
	--         group = 'BlinkPairsMatchParen',
	--         priority = 250,
	--       },
	--     },
	--     debug = false,
	--   }
}
